spring:
  application:
    name: telegram-message-app

  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/message_app_db

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true

app:
  jwt:
    access:
      key: kH4kOjSIBDRlcIwMd1FRDRHf7rkBss4YNUuqgFShabn7Z9PqoFKx165KVQtnTzUT
      expiration: 604800000 # 7 days
    refresh:
      key: umoH5OyB7qqXg9aaTN7MUcCepWfQUDXnQGp0mKSBj5SEPGHJMnfVLUSV0SSmDrpk
      expiration: 2592000000 # 30 days

server:
  servlet:
    context-path: '/message-app'

  port: 8080

springdoc:
  swagger-ui:
    path: ''
    try-it-out-enabled: on

info:
  application:
    base_url: 'http://localhost:${server.port}${server.servlet.context-path}'